### ISSUE TITLE
TransactionId de-synchronisation caused by comms timeout/delay

### ISSUE THREAD

**Issue by OpenlabWA** [samuelventura/SharpModbus#5]
Hey mate, 

Great  project, much appreciated, hope the below helps.

**Problem**
If the timeout period is exceeded when trying to read over a TCP connection, the socket receive buffer isn't flushed before retrying.

**Steps to reproduce**
Place breakpoint as per below inside ModbusSocketStream, it will pause during a read, keep it paused longer than the timeout period, then continue, you will get a partial read exception, subsequent reads on the stream will read the previous transaction and cause a Transaction Id mismatch exception (presuming the data eventually arrives).
![reprosteps](https://user-images.githubusercontent.com/39789524/110489887-b6c67100-812a-11eb-9f98-ca8b4d9d3481.png)

**Potential Solution:**
After an exception, read all available data available from the socket before reading another transaction, or, flush buffer each time before writing our next request, this way the buffer is emptied more readily.

**Add below to IModbusStream Interface**

`void FlushBuffer();`

**Implement FlushBuffer as below in ModbusSocketStream.cs (and all other IModbusStream implementors)**

 `public void FlushBuffer()
  {
      if (socket?.Available == 0) return;
      var AvailableBytes = socket.Available;
      socket.GetStream().Read(new byte[AvailableBytes], 0, AvailableBytes);
  }`

**Flush buffer before writing to stream in ModbusMaster.cs**

`  wrapper.FillRequest(request, 0);
  stream.FlushBuffer();
  stream.Write(request);`

![fix](https://user-images.githubusercontent.com/39789524/110494884-f8591b00-812e-11eb-8a24-bfb35bc4b0fb.png)

**Note**

I think a similar issue occurs in the scanner, I implemented a buffer flush as well on the RTU scanner on an older version however haven't verified if the issue is still present.

Thanks again.

Muzz.

**Comment by samuelventura** [comment]
Thank you for sharing your findings.  Help me confirm commit really fixes your issue before pushing to nuget. Consider this a quick fix and not a thoroughly thought solution. I must say this is not a use case I face internally because we usually close the master and start fresh on any comm error, so I have no way to hard replicate it other than the added test case that adds a delay to the test socket server response. Notice that retrying before the previous response is fully received renders the discard on write useless and throws tid mismatch anyway, hence the shameless delay you will find in the test case. A similar fix for serial comm is pending. Looking forward for your feedback.

**Comment by OpenlabWA** [comment]
Hey Sam, 

This looks to have solved the issue, it's amazing when others are finding issues in use cases you don't even think about testing, my clients find some, ...interesting.. use cases. Even if the response hasn't fully been received for a few packets, at least it will be reset into a state where it can, in future, start communicating, whereas the alternative was getting stuck indefinitely. 

I see you also picked up the ushort transaction Id as well. 

Thanks for your prompt response and the project in general, it's working well on my home solar battery inverter project.
